import optuna
import optuna.visualization as vis

# The two studies generated by your main script
studies_to_evaluate = [
    "universal_mice_sampling_JS_relative",
]

# --- Global Style Settings ---
# Force Arial to prevent Illustrator warnings and increase text size slightly
common_font = dict(family="Arial, Helvetica, sans-serif", size=14, color="black")

# Add massive breathing room around the edges (Left, Right, Top, Bottom)
common_margins = dict(l=150, r=150, t=120, b=150)

# Apply global layout updates
def format_fig(fig, title):
    fig.update_layout(
        title=dict(text=title, font=dict(size=20)),
        font=common_font,
        margin=common_margins,
        # Ensure the background is completely transparent for easy Illustrator editing
        paper_bgcolor='rgba(0,0,0,0)', 
        plot_bgcolor='rgba(0,0,0,0)'
    )
    return fig

for study_name in studies_to_evaluate:
    db_path = f"sqlite:///{study_name}.db"
    
    print(f"\n{'='*60}")
    print(f"Loading Study: {study_name}")
    print(f"{'='*60}")
    
    try:
        study = optuna.load_study(study_name=study_name, storage=db_path)
    except Exception as e:
        print(f"Failed to load {study_name}. Did the optimization finish? Error: {e}")
        continue

    print(f"Total finished trials: {len(study.trials)}")
    if len(study.trials) == 0:
        continue

    print(f"\nGenerating and saving SVG plots for {study_name}...")
    
    # 1. Hyperparameter Importances
    try:
        fig_importance = vis.plot_param_importances(study)
        fig_importance = format_fig(fig_importance, f"Hyperparameter Importances - {study_name}")
        fig_importance.write_image(f"{study_name}_importance.svg", width=1200, height=800)
    except Exception as e:
        print(f"Could not generate importance plot: {e}")

    # 2. Parallel Coordinates
    # Note: Line width cannot be changed natively in Plotly parcoords. 
    # Change the stroke width manually in Adobe Illustrator.
    fig_parallel = vis.plot_parallel_coordinate(study)
    fig_parallel = format_fig(fig_parallel, f"Parallel Coordinates - {study_name}")
    fig_parallel.write_image(f"{study_name}_parallel.svg", width=1600, height=800)

    # 3. Slice Plot
    fig_slice = vis.plot_slice(study)
    fig_slice = format_fig(fig_slice, f"Slice Plot - {study_name}")
    # Rotate x-axis labels on the slice plot to stop horizontal overlapping
    fig_slice.update_xaxes(tickangle=45)
    fig_slice.write_image(f"{study_name}_slice.svg", width=1800, height=800)

    # 4. Contour Plot
    fig_contour = vis.plot_contour(study)
    fig_contour = format_fig(fig_contour, f"Contour Plot - {study_name}")
    fig_contour.write_image(f"{study_name}_contour.svg", width=1600, height=1200)
    
    # 5. Optimization History
    fig_history = vis.plot_optimization_history(study)
    fig_history = format_fig(fig_history, f"Optimization History - {study_name}")
    fig_history.write_image(f"{study_name}_history.svg", width=1200, height=800)

    print(f"Saved SVG figures for {study_name}.")